### ISSUE TITLE
Update JAS-mine-gui to reflect changes in the JAS-mine core

### ISSUE THREAD

**Issue by pbronka** [jasmineRepo/JAS-mine-gui#5]
Changes made to naming of classes in [dev 5.0.0](https://github.com/MRC-CSO-SPHSU/JAS-mine-core/tree/dev/5.0.0) version of JAS-mine core require the GUI to be updated.

Provisional list of required changes:

- [x] Update names of JAS-mine core classes that the GUI refers to, in particular interfaces

**Comment by vkhodygo** [comment]
Please, see #6 
Sorry, it took me some time to go through the code one more time and ensure everything is more or less good. It works with the latest commit of jasmine-core.

**Comment by pbronka** [comment]
Thanks! Sorry, I haven't seen these updates to the GUI.
